### ISSUE TITLE
Plugin not working with Grails 2.3

### ISSUE THREAD

**Issue by tbarnier** [robfletcher/grails-angular-scaffolding#32]
Probably because plugin support evolved in the last release, I have the following error whan running scaffolding:

| Error Error running script ng-generate-all  com.tb.app.Requestmap --stacktrace: startup failed:
_NgGenerate_groovy: 60: unable to resolve class DefaultGrailsTemplateGenerator
 @ line 60, column 1.
1 error
 (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
_NgGenerate_groovy: 60: unable to resolve class DefaultGrailsTemplateGenerator
 @ line 60, column 1.
1 error

```
    at gant.Gant.compileScript(Gant.groovy:631)
    at gant.Gant.this$2$compileScript(Gant.groovy)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1259)
    at gant.Gant$_closure1.doCall(Gant.groovy:129)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1259)
    at org.codehaus.gant.IncludeTargets.leftShift(IncludeTargets.groovy:57)
    at org.codehaus.gant.IncludeTargets$leftShift.call(Unknown Source)
    at NgGenerateAll.run(NgGenerateAll:1)
    at NgGenerateAll$run.call(Unknown Source)
    at gant.Gant.prepareTargets(Gant.groovy:607)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1259)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1259)
```

**Comment by dementiev** [comment]
@tbarnier I have the same exception. Any thoughts how to resolve it?

**Comment by tbarnier** [comment]
I tried to add a "dependsOn" into the plugin on the scaffolding plugins.. didn't work.
As I was in a hurry, I inlined the angular plugin into my root project... and it worked

Cheers

**Comment by robbugh** [comment]
I ran 'grails compile' and managed to get past the above error but now it fails with:

| Error Error executing script NgGenerateAll: startup failed:
_NgGenerate_groovy: 115: The return type of java.lang.Object getTemplateNames() in AngularTemplateGenerator is incompatible with java.util.Set getTemplateNames() in org.codehaus.groovy.grails.scaffolding.AbstractGrailsTemplateGenerator
. At [115:2]  @ line 115, column 2.

**Comment by mikemil** [comment]
I also get the error on line 60 and guessing from what I see - the problem appears to be that class DefaultGrailsTemplateGenerator is not in the 2.3.1 API doc.  Strange because I also saw a recent update by Graeme in the scaffolding plugin that contained an import for that class.

**Comment by mikemil** [comment]
From the looks of the log below, it really just looks like you had problems getting the plugin downloaded and included by maven.   Maybe you can download the plugin from GitHub and install it locally?
There is an unresolved problem with the plugin due to the fact that the scaffolding code because a plugin recently (2.2 or 2.3) and the plugin has not be recompiled with changed dependencies, but that doesn't appear to be your problem from the log below.
Date: Thu, 5 Dec 2013 23:17:13 -0800

**Comment by lduparc** [comment]
Hi everyone,

I try your plugin. The sample works pretty fine for me. I'm working on Mac OSX using grails 2.3.4.
There is a problem when I want to create an Album. Create button seem to not work. I try to find the problem and I come back to you.
- However, When I create a grails project and add < compile ":angular-scaffolding:1.0-SNAPSHOT" > the plugin was not found. If I clone your plugin and run the sample its working well.
- Using your sample. If I add a new simple domain class and  run from the command line "grails ng-generate-all _myDomainClassName_" or "grails ng-generate-views _myDomainClassName_" I have got this error : 

<pre>
I/O exception loading script [scaffoldingPluginDir/scripts/_GrailsGenerate.groovy (No such file or directory)]: scaffoldingPluginDir/scripts/_GrailsGenerate.groovy (No such file or directory)
</pre>

Have you any idea how to fix it ? Any news from previous comments ? It seems to be the same problems.

Thks,

**Comment by sdhaene** [comment]
Hi lduparc,
I bumped into the same issue: with

I/O exception loading script [scaffoldingPluginDir/scripts/_GrailsGenerate.groovy (No such file or directory)]: scaffoldingPluginDir/scripts/_GrailsGenerate.groovy (No such file or directory)

The fix for this is simple: in the _NgGenerate.groovy file, replace
includeTargets << new File("scaffoldingPluginDir/scripts/_GrailsGenerate.groovy")
with
includeTargets << new File("$scaffoldingPluginDir/scripts/_GrailsGenerate.groovy")

The grails scaffolding plugin directory is a variable, hence the required dollar sign.
Cheers,

Stephan

**Comment by rosstang2565** [comment]
Not work in my env.
includeTargets << new File("$scaffoldingPluginDir/scripts/_GrailsGenerate.groovy")
Work!
includeTargets << new File("${scaffoldingPluginDir}/scripts/_GrailsGenerate.groovy")
